name: geSuitChat
main : com.minecraftdimensions.gesuitchat.geSuitChat
version: ${project.version}b-${build.number}
description: Part of the geSuit, this plugin handles all player chat
author: Bloodsplat
softdepend: [Factions, TownyChat, Towny]
commands:
    admin:
        description: Send messages/toggle to the admin channel
        aliases: [a,ac]
        permission: gesuit.chat.channel.admin
        permission-message: §cYou do not have permission for this channel
        usage: /<command>  *(message)
    afk:
        description: Toggles a players afk status
        aliases: [away, brb]
        permission: gesuit.chat.command.afk
        permission-message: §cYou do not have permission for this command
        usage: /<command>
    chatspy:
        description: Allows players to see all messages
        aliases: [cspy,spy,socialspy]
        permission: gesuit.chat.command.chatspy
        permission-message: §cYou do not have permission for this command
        usage: /<command>
    channelinfo:
        description: Gets the information for the channel
        aliases: [channel,c,cinfo]
        permission: gesuit.chat.command.channelinfo
        permission-message: §cYou do not have permission for this command
        usage: |
            /<command> - gets current channels information
            /<command> (channel) - gets the channels information
    factionchat:
        description: Allows the player to talk in the faction channel
        aliases: [fc]
        permission: gesuit.chat.channel.faction
        permission-message: §cYou are unable to talk in this channel
    factionchatally:
        description: Allows the player to talk in the faction ally channel
        aliases: [fca]
        permission: gesuit.chat.channel.factionally
        permission-message: §cYou are unable to talk in this channel 
    factionchatfaction:
        description: Allows the player to talk in the faction ally channel
        aliases: [fcf]
        permission: gesuit.chat.channel.faction
        permission-message: §cYou are unable to talk in this channel
    townychat:
        description: Allows the player to talk in the towny town channel
        aliases: [tc]
        permission: gesuit.chat.channel.town
        permission-message: §cYou are unable to talk in this channel
    townychattown:
        description: Allows the player to talk in towny town channel
        aliases: [tct]
        permission: gesuit.chat.channel.town
        permission-message: §cYou are unable to talk in this channel
    townychatnation:
        description: Allows the player to talk in the towny nation channel
        aliases: [nationchat, nc, tcn]
        permission: gesuit.chat.channel.nation
        permission-message: §cYou are unable to talk in this channel
    formatchannel:
        description: Changes the format of the channel
        aliases: [formatc,cformat,cf]
        permission: gesuit.chat.command.format
        permission-message: §cYou do not have permission for this command
        usage: /<command> (format) - changes the current channels format
    global:
        description: Send messages/toggle to the global channel
        aliases: [g,globalchat,globalchannel,gchannel]
        permission: gesuit.chat.channel.global
        permission-message: §cYou do not have permission for this channel
        usage: |
            /<command> - toggles to global channel
            /<command> (message) - sends message to global channel
    ignore:
        description: Ignores a player from chat
        aliases: [ignoreplayer,playerignore]
        permission: gesuit.chat.command.ignore
        permission-message: §cYou do not have permission for this command
        usage: /<command> (player)
    ignores:
        description: Gives a list of your ignored players
        aliases: [ignorelist,listignores]
        permission: gesuit.chat.command.ignores
        permission-message: §cYou do not have permission for this command
        usage: /<command>
    local:
        description: Send messages/toggle to the local channel
        aliases: [l,lc,localchannel,lchannel,channellocal]
        permission: gesuit.chat.channel.local
        permission-message: §cYou do not have permission for this channel
        usage: |
            /<command> - toggles to local channel
            /<command> (message) - sends message to the local channel
    me:
        description: Sends an emote to the chat on your server
        aliases: [emote]
        permission: gesuit.chat.command.me
        permission-message: §cYou do not have permission for this command
        usage: /<command> (message)
    message:
        description: Send a private message to a player
        aliases: [tell,msg,pm,w,whisper,m]
        permission: gesuit.chat.command.message
        permission-message: §cYou do not have permission for this command
        usage: /<command> (message)
    mute:
        description: Mute a specified player from chat
        permission: gesuit.chat.command.mute
        permission-message: §cYou do not have permission for this command
        usage: /<command> (player)
    muteall:
        description: Mutes all chat proxy wide
        permission: gesuit.chat.command.muteall
        permission-message: §cYou do not have permission for this command
        usage: /<command>
    namecolor:
        description: Changes the players display name color
        permission: gesuit.chat.command.namecolor
        permission-message: §cYou do not have permission for this command
        usage: /<command> (displayname) - &1S&2t&3e&4v&5e
    namecoloroff:
        description: Removes the players name color
        aliases: [nocolor]
        permission: gesuit.chat.command.namecolor
        permission-message: §cYou do not have permission for this command
        usage: /<command>
    nickname:
        description: Changes the players display name
        aliases: [nick,displayname]
        permission: gesuit.chat.command.nickname
        permission-message: §cYou do not have permission for this command
        usage: |
            /<command> (nickname) - nickname self
            /<command> (playername) (nickname) - nickname other player
    nicknameoff:
        description: Removes the players nickname
        aliases: [nickoff,nonick,nonickname]
        permission: gesuit.chat.command.nickname
        permission-message: §cYou do not have permission for this command
        usage: /<command>
    reloadchat:
        description: Reloads the chat config and channels
        aliases: [chatreload]
        permission: gesuit.chat.command.reload
        permission-message: §cYou do not have permission for this command
        usage: /<command> 
    reply:
        description: Sends a reply to the last person who messaged you
        aliases: [r]
        permission: gesuit.chat.command.reply
        permission-message: §cYou do not have permission for this command
        usage: /<command> (message)
    server:
        description: Send messages/toggle to the server channel
        aliases: [s,sc,serverchannel,schannel,channelserver]
        permission: gesuit.chat.channel.server
        permission-message: §cYou do not have permission for this channel
        usage: |
            /<command> - toggles to the server channel
            /<command> (message) - sends a message to the server channel
    tempmute:
        description: Temporarily mutes a player
        aliases: [tmute]
        permission: gesuit.chat.command.tempmute
        permission-message: §cYou do not have permission for this command
        usage: /<command> (player) (time in minutes)
    toggle:
        description: Toggles through your available channels
        aliases: [togglechannel,channeltoggle, ct]
        permission: gesuit.chat.command.toggle
        permission-message: §cYou do not have permission for this command
        usage: /<command>
    unignore:
        description: Unignores a player from chat
        aliases: [uignore,unignoreplayer]
        permission: gesuit.chat.command.ignore
        permission-message: §cYou do not have permission for this command
        usage: /<command> (player)
    unmute:
        description: Unmutes a player from chat
        aliases: [umute, unmuteplayer]
        permission: gesuit.chat.command.mute
        permission-message: §cYou do not have permission for this command
        usage: /<command> (player)
    unmuteall:
        description: Toggles off the proxy wide mute
        permission: gesuit.chat.command.muteall
        permission-message: §cYou do not have permission for this command
        usage: /<command>
permissions:
    gesuit.chat.*:
        description: Gives access to all BungeeSuiteChat commands
        default: op
        children:
            gesuit.chat.admin: true
    gesuit.chat.admin:
        description: Gives access to all BungeeSuiteChat admin commands
        children:
            gesuit.chat.mod: true
            gesuit.chat.command.afk.global: true
            gesuit.chat.command.afk.display: true
            gesuit.chat.nickname.other: true
            gesuit.chat.toggle.bypass: true
            gesuit.chat.command.chatspy: true
            gesuit.chat.command.muteall: true
            gesuit.chat.channel.admin: true
            gesuit.chat.command.reload: true
            gesuit.chat.command.nickname.other: true
            gesuit.chat.vip: true
            gesuit.chat.command.channelinfo.format: true
    gesuit.chat.mod:
        description: Gives access to all BungeeSuiteChat mod commands
        children:
            gesuit.chat.command.mute: true
            gesuit.chat.command.tempmute: true
            gesuit.chat.user: true
    gesuit.chat.user:
        description: Gives access to all BungeeSuiteChat user commands
        children:
            gesuit.chat.channel.server: true
            gesuit.chat.channel.local: true
            gesuit.chat.channel.global: true
            gesuit.chat.channel.faction: true
            gesuit.chat.channel.factionally: true
            gesuit.chat.channel.nation: true
            gesuit.chat.channel.town: true
            gesuit.chat.command.afk: true
            gesuit.chat.command.channelinfo: true
            gesuit.chat.command.ignore: true
            gesuit.chat.command.ignores: true
            gesuit.chat.command.message: true
            gesuit.chat.command.reply: true
            gesuit.chat.command.toggle: true
    gesuit.chat.vip:
        description: Gives the player access to the vip commands
        children:
            gesuit.chat.command.nickname: true
            gesuit.chat.command.me: true
            gesuit.chat.user: true
            gesuit.chat.color: true

        